spring:
  datasource:
    url: jdbc:mysql://localhost:4306/conduit
    username: conduit
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # everytime start application it will use new empty tables
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect

server:
  servlet:
    context-path: /api
